[project]
name = "practical-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "sympy>=1.14.0",
    "torch>=2.7.1",
    "torchviz>=0.0.3",
]
